<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Vystral.Core</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.Data.Sqlite" Version="10.0.12" />
    <PackageReference Include="Dapper" Version="2.1.89" />
  </ItemGroup>
  <ItemGroup>
    <InternalsVisibleTo Include="Vystral.Tests" />
  </ItemGroup>
</Project>
